### ISSUE TITLE
chown: changing ownership of '/cwa-book-ingest': Invalid argument

### ISSUE THREAD

**Issue by davecburke** [calibrain/calibre-web-automated-book-downloader#14]
I'm trying to get this working on a Proxmox LWC but I'm getting this error:
calibre-web-automated-calibre-web-automated-book-downloader-1  | chown: changing ownership of '/cwa-book-ingest': Invalid argument
calibre-web-automated-calibre-web-automated-book-downloader-1 exited with code 1

This is my compose:
`services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Melbourne
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - ./config:/config
      - /mnt/data/media/cwa-book-ingest:/cwa-book-ingest
      - /mnt/data/media/books/cwa-library:/calibre-library
      # - /mnt/data/media/books:/books #Optional
      #- /path/to/your/gmail/credentials.json:/app/calibre-web/gmail.json #Optional
    ports:
      - 8084:8083 # Change the first number to change the port you want to access the Web UI, not the second
    restart: unless-stopped
  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    environment:
      FLASK_PORT: 8084
      FLASK_DEBUG: false
      CLOUDFLARE_PROXY_URL: http://cloudflarebypassforscraping:8000
      INGEST_DIR: /cwa-book-ingest
      BOOK_LANGUAGE: en
      PUID: 0
      PGID: 0
    ports:
      - 8085:8084
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8084/request/api/status
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    volumes:
      # This is where the books will be downloaded to, usually it would be 
      # the same as whatever you gave in "calibre-web-automated"
      - /mnt/data/media/cwa-book-ingest:${INGEST_DIR:-/cwa-book-ingest}
  cloudflarebypassforscraping:
    image: ghcr.io/sarperavci/cloudflarebypassforscraping:latest
    restart: unless-stopped
networks: {}
`

Any help would be appreciated. Thanks

**Comment by calibrain** [comment]
Oh, in your environment, instead of `PUID` and `GUID` please use `UID` and `GID` for `calibre-web-automated-book-downloader` (basically the env name is different between the two)
