### ISSUE TITLE
chown failure prevents docker start

### ISSUE THREAD

**Issue by chiefcastor** [calibrain/calibre-web-automated-book-downloader#19]
I am running docker in a proxmox unprivileged LXC. The ingest directory is on my NAS and the LXC/docker are not permitted to chown the directory.  The docker never starts and this all printed in the logs over and over again:

chown: changing ownership of '/cwa-book-ingest': Operation not permitted

It worked yesterday (Dec 19).

Can the docker be allowed to start when the chown fails?

**Comment by calibrain** [comment]
Hey, really sorry about that ! 
I fixed it by just ignoring the error !

https://github.com/calibrain/calibre-web-automated-book-downloader/commit/78e423e8a513c39c3c67b4a0dbd99b88a6abb135
