### ISSUE TITLE
SSL error - a configuration issue?

### ISSUE THREAD

**Issue by noseboy** [calibrain/calibre-web-automated-book-downloader#26]
I can't search for anything and I get this in the logs

2024-12-24 23:16:06,032 - network - WARNING - Retrying GET https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&sort=&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&lang=en&q=drew%20hayes in 15 seconds due to error: HTTPSConnectionPool(host='annas-archive.org', port=443): Max retries exceeded with url: /search?index=&page=1&display=table&acc=aa_download&acc=external_download&sort=&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&lang=en&q=drew%20hayes (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'annas-archive.org'. (_ssl.c:1000)")))

If I shell into the container I can execute curl against other sites like www.google.com, so I presume this is an SSL configuration issue?

I am running WITHOUT calibre-web-automated, if that makes a difference, as I just want the book files.

**Comment by calibrain** [comment]
Hello !
Do you have anything like a VPN or a unique network configuration ?
This might happen when you have some kind of certificate injection
 
I checked and `annas-archive.org` is still valid and didnt lapse during that time either
```
Issued On	Tuesday, December 17, 2024 at 3:58:40 AM
Expires On	Monday, March 17, 2025 at 5:57:00 AM
```

**Comment by noseboy** [comment]
No, no VPN set up. And working for non-https access. :(

**Comment by calibrain** [comment]
Does curl `https://annas-archive.org/` works from inside the image (the cloudflarebypass one) for you ?

**Comment by noseboy** [comment]
No, curl is not recognised from inside the cloudflarebypass one.  "curl: not found".  From inside calibre-web-automated-book-downloader, I get: curl: (60) SSL: no alternative certificate subject name matches target host name 'annas-archive.org'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by noseboy** [comment]
Aha!  Issue identified:

dig annas-archive.org


; <<>> DiG 9.18.28-1~deb12u2-Debian <<>> annas-archive.org

;; global options: +cmd

;; Got answer:

;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1206

;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1


;; OPT PSEUDOSECTION:

; EDNS: version: 0, flags:; udp: 512

;; QUESTION SECTION:

;annas-archive.org. IN A


;; ANSWER SECTION:

annas-archive.org. 971 IN CNAME www.ukispcourtorders.co.uk.

www.ukispcourtorders.co.uk. 312 IN CNAME ukispblk.vo.llnwd.net.

ukispblk.vo.llnwd.net. 39 IN A 87.248.205.0


;; Query time: 8 msec

;; SERVER: 192.168.0.1#53(192.168.0.1) (UDP)

;; WHEN: Thu Dec 26 21:11:24 GMT 2024

;; MSG SIZE  rcvd: 137


So it's a docker DNS issue I need to work out

**Comment by noseboy** [comment]
DNS set to 8.8.8.8 and all working - please close.

**Comment by calibrain** [comment]
Glad you were able to figure it out !
Awesome job
