### ISSUE TITLE
language switch

### ISSUE THREAD

**Issue by Famku** [calibrain/calibre-web-automated-book-downloader#4]
Hi,

Is it possible to change the search language in the app?

**Comment by calibrain** [comment]
You are in luck, @BastianLo just merged a PR to enable that feature 😄 
You can set it in the environment variable of the docker :


`BOOK_LANGUAGE` | Preferred language for books | en

Acceptable languages are 
```
English [en]
Chinese [zh]
Russian [ru]
Spanish [es]
French [fr]
German [de]
Italian [it]
Portuguese [pt]
Polish [pl]
Bulgarian [bg]
Dutch [nl]
Japanese [ja]
Arabic [ar]
Hebrew [he]
Hungarian [hu]
Latin [la]
Czech [cs]
Korean [ko]
Turkish [tr]
Ukrainian [uk]
Indonesian [id]
Romanian [ro]
Greek [el]
Lithuanian [lt]
Bangla [bn]
Traditional Chinese [zh‑Hant]
Afrikaans [af]
Catalan [ca]
Swedish [sv]
Thai [th]
Hindi [hi]
Irish [ga]
Latvian [lv]
Kannada [kn]
Serbian [sr]
Tibetan [bo]
Danish [da]
Persian [fa]
Croatian [hr]
Slovak [sk]
Javanese [jv]
Vietnamese [vi]
Urdu [ur]
Finnish [fi]
Norwegian [no]
Kinyarwanda [rw]
Tamil [ta]
Belarusian [be]
Kazakh [kk]
Mongolian [mn]
Georgian [ka]
Slovenian [sl]
Esperanto [eo]
Galician [gl]
Marathi [mr]
Filipino [fil]
Gujarati [gu]
Malayalam [ml]
Kyrgyz [ky]
Quechua [qu]
Azerbaijani [az]
Swahili [sw]
Bashkir [ba]
Punjabi [pa]
Malay [ms]
Telugu [te]
Albanian [sq]
Uyghur [ug]
Armenian [hy]
Shan [shn]
```

**Comment by Borriborri** [comment]
can we add multiple languages?

**Comment by calibrain** [comment]
@Borriborri yes
You can change the book language environment variable to be a coma separated one, for example 

`BOOK_LANGUAGE=en,fr,es` would search for all books in English, French or Spanish

**Comment by Al4ndil** [comment]
Hi @calibrain 
How can i set BOOK_LANGUAGE to ALL by default ?
Thank you :)

**Comment by calibrain** [comment]
@Al4ndil You could set `BOOK_LANGUAGE` as empty, it should work I think
(if not, you can also just put every language in there, like `BOOK_LANGUAGE=en,zh,ru,es,fr,de,it,pt,pl,bg,nl,ja,ar,he,hu,la,cs,ko,tr,uk,id,ro,el,lt,bn,zh‑Hant,af,ca,sv,th,hi,ga,lv,kn,sr,bo,da,fa,hr,sk,jv,vi,ur,fi,no,rw,ta,be,kk,mn,ka,sl,eo,gl,mr,fil,gu,ml,ky,qu,az,sw,ba,pa,ms,te,sq,ug,hy,shn`
